### ISSUE TITLE
Executed messages may be empty, but without error

### ISSUE THREAD

**Issue by pronvis** [Anchor-Protocol/anchor-token-contracts#13]
This error: https://github.com/Anchor-Protocol/anchor-token-contracts/blob/54fb31c0ef037b8124a0f4c5bbbe91bb3b5abdd5/contracts/gov/src/contract.rs#L496
returns only if `execute_data` is None, but it also may be `Some(vec![])`. 
In case of empty vector you do not return error there.

**Comment by ezaanm** [comment]
Thanks again @pronvis for your thorough review. Fixed in https://github.com/Anchor-Protocol/anchor-token-contracts/pull/16, will close this issue after PR merges.

**Comment by ezaanm** [comment]
Closing this Issue and echoing the reason from https://github.com/Anchor-Protocol/anchor-token-contracts/pull/16.

As @MSNTCS pointed out in the comment above we should not implement this change. The reason is because Poll's should be allowed to exist with empty execute_msgs such as a text only based poll. This change would have marked those Poll's as failed while they really should be executed
